"""
Generates rust-core/src/standard_font_metrics.rs: flattened
[width_per_char_code; 256] tables for the 14 PDF "standard" fonts (the ones
every PDF-conforming reader must support without embedding), across the two
encodings real-world PDF producers actually use for them (StandardEncoding,
WinAnsiEncoding).

Why this exists: a huge fraction of real-world PDFs (anything using
Helvetica/Times/Courier/Arial/etc. without embedding a font program) carry
NO /Widths array at all -- they rely on every reader already knowing these
metrics. Our own reportlab-generated test fixture is exactly this case (see
rust-core/resources/README.md). Without this table, "parse /Widths" would
do nothing for a very common category of real PDF.

Source data (fetched, not committed raw -- see step 1 below):
  - src/core/metrics.js and src/core/encodings.js from mozilla/pdf.js
    (Apache License 2.0). metrics.js's glyph-width tables are themselves a
    derivative of Adobe's public "Font Metrics for the PDF Core 14 Fonts"
    package, which Adobe's own accompanying notice permits redistributing
    for any purpose provided copyright notices are retained -- the same
    terms every PDF library (poppler, PDFBox, pdfminer.six, jsPDF, ...)
    relies on to bundle the equivalent tables.

Usage:
    curl -sL -o /tmp/pdfjs_metrics.js \\
      https://raw.githubusercontent.com/mozilla/pdf.js/master/src/core/metrics.js
    curl -sL -o /tmp/pdfjs_encodings.js \\
      https://raw.githubusercontent.com/mozilla/pdf.js/master/src/core/encodings.js
    python3 tools/generate_standard_font_metrics.py
"""
import re
import json

METRICS_JS = "/tmp/pdfjs_metrics.js"
ENCODINGS_JS = "/tmp/pdfjs_encodings.js"
OUT_PATH = "rust-core/src/standard_font_metrics.rs"

FONTS = [
    "Courier", "Courier-Bold", "Courier-BoldOblique", "Courier-Oblique",
    "Helvetica", "Helvetica-Bold", "Helvetica-BoldOblique", "Helvetica-Oblique",
    "Times-Roman", "Times-Bold", "Times-BoldItalic", "Times-Italic",
]
ENCODINGS = ["StandardEncoding", "WinAnsiEncoding"]
DEFAULT_WIDTH = 500  # fallback for the rare glyph with no metric entry


def extract_glyph_widths(js: str, name: str) -> dict:
    dot_pat = r"t\." + re.escape(name)
    bracket_pat = r"t\[" + re.escape(json.dumps(name)) + r"\]"
    accessor = r"(?:" + dot_pat + r"|" + bracket_pat + r")"

    m = re.search(accessor + r"\s*=\s*(\d+);", js)
    if m:
        return {"__all__": int(m.group(1))}  # monospace (Courier family)

    m = re.search(accessor + r"\s*=\s*getLookupTableFactory\(function \(t\) \{(.*?)\n {2}\}\);", js, re.DOTALL)
    if not m:
        raise ValueError(f"couldn't find metrics block for {name}")
    return {
        gm.group(1): int(gm.group(2))
        for gm in re.finditer(r"t\.([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(\d+);", m.group(1))
    }


def extract_encoding_array(js: str, varname: str) -> list:
    m = re.search(r"const " + varname + r"\s*=\s*\[(.*?)\];", js, re.DOTALL)
    return re.findall(r'"((?:[^"\\]|\\.)*)"', m.group(1))


def rust_ident(name: str) -> str:
    return name.replace("-", "_").upper()


def main():
    metrics_js = open(METRICS_JS).read()
    encodings_js = open(ENCODINGS_JS).read()

    font_glyph_widths = {f: extract_glyph_widths(metrics_js, f) for f in FONTS}
    glyph_by_code = {enc: extract_encoding_array(encodings_js, enc) for enc in ENCODINGS}
    for enc, arr in glyph_by_code.items():
        assert len(arr) == 256, f"{enc} expected 256 entries, got {len(arr)}"

    lines = [
        "// AUTO-GENERATED by tools/generate_standard_font_metrics.py. Do not hand-edit.",
        "//",
        "// Standard-14 PDF core font width metrics, flattened to (encoding x font)",
        "// -> [width_per_char_code; 256] tables so runtime lookup is a single array",
        "// index, no glyph-name string matching needed at parse time.",
        "//",
        "// Source data: PDF.js (https://github.com/mozilla/pdf.js), Apache License 2.0,",
        "// itself derived from Adobe's public \"Font Metrics for the PDF Core 14 Fonts\"",
        "// package. See rust-core/resources/README.md for full provenance.",
        "",
    ]

    table_names = []
    for enc in ENCODINGS:
        codes = glyph_by_code[enc]
        for font in FONTS:
            glyph_widths = font_glyph_widths[font]
            widths = []
            for code in range(256):
                glyph = codes[code]
                if "__all__" in glyph_widths:
                    w = glyph_widths["__all__"]
                elif glyph and glyph in glyph_widths:
                    w = glyph_widths[glyph]
                else:
                    w = DEFAULT_WIDTH
                widths.append(w)
            table_name = f"{rust_ident(font)}_{enc.upper()}"
            table_names.append((font, enc, table_name))
            lines.append(f"pub static {table_name}: [u16; 256] = [")
            for i in range(0, 256, 16):
                lines.append(f"    {', '.join(str(w) for w in widths[i:i + 16])},")
            lines.append("];")
            lines.append("")

    lines += [
        "/// Looks up the flattened width table for a standard-14 base font name and",
        "/// PDF /Encoding name. Returns None for non-standard (embedded/subset) fonts,",
        "/// which must supply their own /Widths or /W array instead.",
        "pub fn standard_font_table(base_font: &str, encoding: &str) -> Option<&'static [u16; 256]> {",
        '    let enc_key = if encoding == "WinAnsiEncoding" { "WinAnsiEncoding" } else { "StandardEncoding" };',
        "    match (base_font, enc_key) {",
    ]
    for font, enc, table_name in table_names:
        lines.append(f'        ("{font}", "{enc}") => Some(&{table_name}),')
    lines += [
        "        _ => None,",
        "    }",
        "}",
        "",
        "/// A handful of very common non-standard-but-metrically-equivalent BaseFont",
        "/// names (Arial has never needed its own AFM file precisely because it was",
        "/// designed to be width-compatible with Helvetica; same story for the other",
        "/// two families below).",
        "pub fn normalize_base_font_name(name: &str) -> &str {",
        "    match name {",
        '        "Arial" => "Helvetica",',
        '        "Arial,Bold" | "Arial-Bold" | "Arial-BoldMT" => "Helvetica-Bold",',
        '        "Arial,Italic" | "Arial-Italic" | "Arial-ItalicMT" => "Helvetica-Oblique",',
        '        "Arial,BoldItalic" | "Arial-BoldItalicMT" => "Helvetica-BoldOblique",',
        '        "TimesNewRoman" | "TimesNewRomanPSMT" => "Times-Roman",',
        '        "TimesNewRoman,Bold" | "TimesNewRomanPS-BoldMT" => "Times-Bold",',
        '        "TimesNewRoman,Italic" | "TimesNewRomanPS-ItalicMT" => "Times-Italic",',
        '        "TimesNewRoman,BoldItalic" | "TimesNewRomanPS-BoldItalicMT" => "Times-BoldItalic",',
        '        "CourierNew" | "CourierNewPSMT" => "Courier",',
        '        "CourierNew,Bold" | "CourierNewPS-BoldMT" => "Courier-Bold",',
        "        other => other,",
        "    }",
        "}",
    ]

    with open(OUT_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT_PATH} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
